# Generated by Django 5.2.6 on 2025-10-08 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_followers_alter_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
