# Generated by Django 5.2.6 on 2025-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('friend_request', 'Заявка в друзья'), ('comment', 'Комментарий'), ('message', 'Сообщение')], max_length=25),
        ),
    ]
