# Generated by Django 5.2.6 on 2025-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('friend_request', 'Заявка в друзья'), ('comment', 'Комментарий'), ('message', 'Сообщение'), ('community_join', 'Подписка на вашу группу')], max_length=25),
        ),
    ]
